#!/usr/bin/with-contenv sh

PUID=${PUID:-911}
PGID=${PGID:-911}

if [ ! "$(id -u dummy)" -eq "$PUID" ]; then usermod -o -u "$PUID" dummy ; fi
if [ ! "$(id -g dummy)" -eq "$PGID" ]; then groupmod -o -g "$PGID" dummy ; fi

echo "
GID/UID
-------------------------------------
User uid:    $(id -u dummy)
User gid:    $(id -g dummy)
-------------------------------------
"
chown dummy:dummy \
	/app \
	/config \
	/cronlist \
	/var/lock/rclone.lock