#!/usr/bin/with-contenv sh

# change crontab file
if [[ -n "$CRON_SCHEDULE" ]]; then
  sed -i -e 's|0 \* \* \* \*|'"$CRON_SCHEDULE"'|g' /defaults/rclone_cron
fi

echo "crontab => $(cat /defaults/rclone_cron)"

# set crontab
crontab -u dummy /defaults/rclone_cron

# create empty config file
touch /config/rclone.conf

# permissions
chown -R dummy:dummy \
	/app
chown dummy:dummy \
	/config/rclone.conf
chmod +x \
	/app/rclone.sh
chmod 777 \
	/var/lock